### PR TITLE
Migrate to Dart Sass from LibSass

### PR DESCRIPTION
**Pull request by jon-kirwan**
## What

Migrate to Dart Sass from LibSass.

## Why

- LibSass is now [deprecated](https://sass-lang.com/blog/libsass-is-deprecated/)
- Making changes ahead of Design System team dropping support for LibSass https://github.com/alphagov/govuk-frontend/discussions/2632.

## Visual Changes

None.

## How can I test these changes?

- run `yarn jasmine:prepare` (or run `bundle exec rake app:assets:clobber app:assets:precompile`)
- what should happen? The Sass files should be compiled. Keep an eye on the command line for warnings indicating the compilation process using Dart Sass
```
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: math.div(300%, 4) or calc(300% / 4)
More info and automated migrator: https://sass-lang.com/d/slash-div
   │
26 │   three-quarters: (300% / 4),
   │                    ^^^^^^^^
   ...
```
- the `/builds` folder: `app/assets/builds` should now be populated with CSS files. Note, the 
- subsequently, all assets ought to be generated successfully within the `/public` directory
- no test failures to indicate the correct number of stylesheets are generated
- deploy to Integration. You'll notice that in the '**build and publish image**' task, the steps taken resemble those mentioned earlier, `dartsass-rails` is bundled and any Dart Sass warnings encountered during the compilation process are reported)
- inspect several pages, e.g. [
  manage your GOV.UK email subscriptions](https://www.integration.publishing.service.gov.uk/email/manage), [what do you want to get emails about?](https://www.integration.publishing.service.gov.uk/email-signup?link=/money), [get emails from GOV.UK](https://www.integration.publishing.service.gov.uk/foreign-travel-advice/canada/email-signup), [how often do you want to get emails?](https://www.integration.publishing.service.gov.uk/email/subscriptions/new?topic_id=statistics-with-1-research-and-statistic-5e2982632b) to ensure the absence of errors.

## Anything else

Once the PR gets the green light, any temporary commits and references to local gems e.g. `gem "govuk_publishing_components", path: "../govuk_publishing_components"` will be removed.

See:
- https://github.com/alphagov/collections/pull/3447
- https://github.com/alphagov/govuk_publishing_components/pull/3726
- https://github.com/alphagov/static/pull/3190
- https://github.com/alphagov/govuk-developer-docs/pull/4216.

### CODE REVIEW

**Review by MartinJJones — COMMENTED** [review]
Works great for me when testing locally 👍 

Just wanted to ask if we will also include the generated files from running the `./bin/rails dartsass:install` command to help watch for any CSS changes, similar to https://github.com/alphagov/government-frontend/commit/1ed1fae642826abd42987a3ea1f845a83cfcc11d

If so, I think we would also need to create a separate PR to add support for this in govuk-docker

**Comment by jon-kirwan** [comment]
> Works great for me when testing locally 👍
> 
> Just wanted to ask if we will also include the generated files from running the `./bin/rails dartsass:install` command to help watch for any CSS changes, similar to [alphagov/government-frontend@1ed1fae](https://github.com/alphagov/government-frontend/commit/1ed1fae642826abd42987a3ea1f845a83cfcc11d)

I'm on the fence about adding it here because of the limited number of pages (perhaps around 4?) and the difficulties of testing frontend changes without being signed in but perhaps I should consider enabling it here? What do you think? It might have been useful with the recent cross service header changes.

**Comment by MartinJJones** [comment]
> I'm on the fence about adding it here because of the limited number of pages (perhaps around 4?) and the difficulties of testing frontend changes without being signed in but perhaps I should consider enabling it here? What do you think? It might have been useful with the recent cross service header changes.

Thanks, these are good points, sounds reasonable to me for this application, and you have also already added a section on this in the developer docs should another developer want to add support for this in the future - https://github.com/alphagov/govuk-developer-docs/blob/3bac7fd893e0442f1e1afd3a28bdebe600bd5174/source/manual/migrate-to-dart-sass-from-libsass.html.md#watch-mode

**Review by MartinJJones — COMMENTED** [review]
Changes look good to me, nice work!

Happy to approve the PR once the merge conflict is resolved, I think this will likely solve itself when testing is complete and "TEMP" commits removed/squashed.

**Review by MartinJJones — APPROVED** [review]
Changes look good to me 👍

**Pull request merged**
